# Set up

In [1]:
project_folder = "/content/drive/MyDrive/weather_predictor"

from google.colab import drive
drive.mount('/content/drive')

%cd "{project_folder}"
!git pull

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/weather_predictor
Already up to date.

# Cài đặt môi trường

In [2]:
!git pull
!pip install -r requirements.txt

Already up to date.
Obtaining file:///content/drive/MyDrive/weather_predictor (from -r requirements.txt (line 17))
  Preparing metadata (setup.py) ... done
Requirement already satisfied: tensorflow in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 1)) (2.18.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 2)) (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 3)) (2.0.2)
Collecting dvc (from -r requirements.txt (line 4))
  Downloading dvc-3.59.1-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 5)) (3.10.0)
Collecting mlflow==2.2.2 (from -r requirements.txt (line 6))
  Downloading mlflow-2.2.2-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: notebook in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 7)) (6.5.7)
Collecting scikit-learn==1.3.0 (from -r requirements.txt (line 8))
  Downloading scikit_learn-1.3.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting python-box==6.0.2 (from -r requirements.txt (line 9))
  Downloading python_box-6.0.2-py3-none-any.whl.metadata (7.7 kB)
Requirement already satisfied: pyYAML in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 10)) (6.0.2)
Collecting types-PyYAML (from -r requirements.txt (line 11))
  Downloading types_pyyaml-6.0.12.20250402-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: seaborn in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 12)) (0.13.2)
Requirement already satisfied: xgboost in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 13)) (2.1.4)
Requirement already satisfied: lightgbm in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 14)) (4.5.0)
Requirement already satisfied: imbalanced-learn in /usr/local/lib/python3.11/dist-packages (from -r requirements.txt (line 15)) (0.13.0)
Collecting zzzz_mylib_23_4==0.26 (from -r requirements.txt (line 16))
  Downloading zzzz_mylib_23_4-0.26-py3-none-any.whl.metadata (174 bytes)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.2.2->-r requirements.txt (line 6)) (8.1.8)
Collecting cloudpickle<3 (from mlflow==2.2.2->-r requirements.txt (line 6))
  Downloading cloudpickle-2.2.1-py3-none-any.whl.metadata (6.9 kB)
Collecting databricks-cli<1,>=0.8.7 (from mlflow==2.2.2->-r requirements.txt (line 6))
  Downloading databricks_cli-0.18.0-py2.py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: entrypoints<1 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.2.2->-r requirements.txt (line 6)) (0.4)
Requirement already satisfied: gitpython<4,>=2.1.0 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.2.2->-r requirements.txt (line 6)) (3.1.44)
Collecting protobuf<5,>=3.12.0 (from mlflow==2.2.2->-r requirements.txt (line 6))
  Downloading protobuf-4.25.7-cp37-abi3-manylinux2014_x86_64.whl.metadata (541 bytes)
Collecting pytz<2023 (from mlflow==2.2.2->-r requirements.txt (line 6))
  Downloading pytz-2022.7.1-py2.py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.2.2->-r requirements.txt (line 6)) (2.32.3)
Collecting packaging<24 (from mlflow==2.2.2->-r requirements.txt (line 6))
  Downloading packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting importlib-metadata!=4.7.0,<7,>=3.7.0 (from mlflow==2.2.2->-r requirements.txt (line 6))
  Downloading importlib_metadata-6.11.0-py3-none-any.whl.metadata (4.9 kB)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.2.2->-r requirements.txt (line 6)) (0.5.3)
Collecting alembic<2 (from mlflow==2.2.2->-r requirements.txt (line 6))
  Downloading alembic-1.15.2-py3-none-any.whl.metadata (7.3 kB)
Collecting docker<7,>=4.0.0 (from mlflow==2.2.2->-r requirements.txt (line 6))
  Downloading docker-6.1.3-py3-none-any.whl.metadata (3.5 kB)
Collecting Flask<3 (from mlflow==2.2.2->-r requirements.txt (line 6))
  Downloading flask-2.3.3-py3-none-any.whl.metadata (3.6 kB)
Collecting numpy (from -r requirements.txt (line 3))
  Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 3.9 MB/s eta 0:00:00
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.2.2->-r requirements.txt (line 6)) (1.14.1)
Collecting querystring-parser<2 (from mlflow==2.2.2->-r requirements.txt (line 6))
  Downloading querystring_parser-1.2.4-py2.py3-none-any.whl.metadata (559 bytes)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.2.2->-r requirements.txt (line 6)) (2.0.40)
Collecting pyarrow<12,>=4.0.0 (from mlflow==2.2.2->-r requirements.txt (line 6))
  Downloading pyarrow-11.0.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: shap<1,>=0.40 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.2.2->-r requirements.txt (line 6)) (0.47.2)
Requirement already satisfied: markdown<4,>=3.3 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.2.2->-r requirements.txt (line 6)) (3.8)
Collecting gunicorn<21 (from mlflow==2.2.2->-r requirements.txt (line 6))
  Downloading gunicorn-20.1.0-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: Jinja2<4,>=2.11 in /usr/local/lib/python3.11/dist-packages (from mlflow==2.2.2->-r requirements.txt (line 6)) (3.1.6)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.3.0->-r requirements.txt (line 8)) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn==1.3.0->-r requirements.txt (line 8)) (3.6.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (25.2.10)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (0.6.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (3.4.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (3.0.1)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (4.13.2)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (1.17.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (1.71.0)
Requirement already satisfied: tensorboard<2.19,>=2.18 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (2.18.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (3.8.0)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (3.13.0)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (0.4.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.11/dist-packages (from tensorflow->-r requirements.txt (line 1)) (0.37.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->-r requirements.txt (line 2)) (2.8.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->-r requirements.txt (line 2)) (2025.2)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (25.3.0)
Collecting celery (from dvc->-r requirements.txt (line 4))
  Downloading celery-5.5.1-py3-none-any.whl.metadata (22 kB)
Collecting colorama>=0.3.9 (from dvc->-r requirements.txt (line 4))
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting configobj>=5.0.9 (from dvc->-r requirements.txt (line 4))
  Downloading configobj-5.0.9-py2.py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: distro>=1.3 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (1.9.0)
Collecting dpath<3,>=2.1.0 (from dvc->-r requirements.txt (line 4))
  Downloading dpath-2.2.0-py3-none-any.whl.metadata (15 kB)
Collecting dulwich (from dvc->-r requirements.txt (line 4))
  Downloading dulwich-0.22.8-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.9 kB)
Collecting dvc-data<3.17,>=3.16.2 (from dvc->-r requirements.txt (line 4))
  Downloading dvc_data-3.16.9-py3-none-any.whl.metadata (5.0 kB)
Collecting dvc-http>=2.29.0 (from dvc->-r requirements.txt (line 4))
  Downloading dvc_http-2.32.0-py3-none-any.whl.metadata (1.3 kB)
Collecting dvc-objects (from dvc->-r requirements.txt (line 4))
  Downloading dvc_objects-5.1.0-py3-none-any.whl.metadata (3.7 kB)
Collecting dvc-render<2,>=1.0.1 (from dvc->-r requirements.txt (line 4))
  Downloading dvc_render-1.0.2-py3-none-any.whl.metadata (5.4 kB)
Collecting dvc-studio-client<1,>=0.21 (from dvc->-r requirements.txt (line 4))
  Downloading dvc_studio_client-0.21.0-py3-none-any.whl.metadata (4.3 kB)
Collecting dvc-task<1,>=0.3.0 (from dvc->-r requirements.txt (line 4))
  Downloading dvc_task-0.40.2-py3-none-any.whl.metadata (10.0 kB)
Collecting flatten_dict<1,>=0.4.1 (from dvc->-r requirements.txt (line 4))
  Downloading flatten_dict-0.4.2-py2.py3-none-any.whl.metadata (9.2 kB)
Collecting flufl.lock<9,>=8.1.0 (from dvc->-r requirements.txt (line 4))
  Downloading flufl_lock-8.1.0-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: fsspec>=2024.2.0 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (2025.3.2)
Collecting funcy>=1.14 (from dvc->-r requirements.txt (line 4))
  Downloading funcy-2.0-py2.py3-none-any.whl.metadata (5.9 kB)
Collecting grandalf<1,>=0.7 (from dvc->-r requirements.txt (line 4))
  Downloading grandalf-0.8-py3-none-any.whl.metadata (1.7 kB)
Collecting gto<2,>=1.6.0 (from dvc->-r requirements.txt (line 4))
  Downloading gto-1.7.2-py3-none-any.whl.metadata (4.7 kB)
Collecting hydra-core>=1.1 (from dvc->-r requirements.txt (line 4))
  Downloading hydra_core-1.3.2-py3-none-any.whl.metadata (5.5 kB)
Collecting iterative-telemetry>=0.0.7 (from dvc->-r requirements.txt (line 4))
  Downloading iterative_telemetry-0.0.10-py3-none-any.whl.metadata (4.1 kB)
Collecting kombu (from dvc->-r requirements.txt (line 4))
  Downloading kombu-5.5.3-py3-none-any.whl.metadata (3.5 kB)
Requirement already satisfied: networkx>=2.5 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (3.4.2)
Collecting omegaconf (from dvc->-r requirements.txt (line 4))
  Downloading omegaconf-2.3.0-py3-none-any.whl.metadata (3.9 kB)
Collecting pathspec>=0.10.3 (from dvc->-r requirements.txt (line 4))
  Downloading pathspec-0.12.1-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: platformdirs<5,>=3.1.1 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (4.3.7)
Requirement already satisfied: psutil>=5.8 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (5.9.5)
Requirement already satisfied: pydot>=1.2.4 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (3.0.4)
Collecting pygtrie>=2.3.2 (from dvc->-r requirements.txt (line 4))
  Downloading pygtrie-2.5.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: pyparsing>=2.4.7 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (3.2.3)
Requirement already satisfied: rich>=12 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (13.9.4)
Collecting ruamel.yaml>=0.17.11 (from dvc->-r requirements.txt (line 4))
  Downloading ruamel.yaml-0.18.10-py3-none-any.whl.metadata (23 kB)
Collecting scmrepo<4,>=3.3.8 (from dvc->-r requirements.txt (line 4))
  Downloading scmrepo-3.3.10-py3-none-any.whl.metadata (4.8 kB)
Collecting shortuuid>=0.5 (from dvc->-r requirements.txt (line 4))
  Downloading shortuuid-1.0.13-py3-none-any.whl.metadata (5.8 kB)
Collecting shtab<2,>=1.3.4 (from dvc->-r requirements.txt (line 4))
  Downloading shtab-1.7.2-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: tabulate>=0.8.7 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (0.9.0)
Collecting tomlkit>=0.11.1 (from dvc->-r requirements.txt (line 4))
  Downloading tomlkit-0.13.2-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: tqdm<5,>=4.63.1 in /usr/local/lib/python3.11/dist-packages (from dvc->-r requirements.txt (line 4)) (4.67.1)
Collecting voluptuous>=0.11.7 (from dvc->-r requirements.txt (line 4))
  Downloading voluptuous-0.15.2-py3-none-any.whl.metadata (20 kB)
Collecting zc.lockfile>=1.2.1 (from dvc->-r requirements.txt (line 4))
  Downloading zc.lockfile-3.0.post1-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->-r requirements.txt (line 5)) (1.3.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.11/dist-packages (from matplotlib->-r requirements.txt (line 5)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.11/dist-packages (from matplotlib->-r requirements.txt (line 5)) (4.57.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.11/dist-packages (from matplotlib->-r requirements.txt (line 5)) (1.4.8)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.11/dist-packages (from matplotlib->-r requirements.txt (line 5)) (11.1.0)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 7)) (6.4.2)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 7)) (24.0.1)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 7)) (23.1.0)
Requirement already satisfied: traitlets>=4.2.1 in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 7)) (5.7.1)
Requirement already satisfied: jupyter-core>=4.6.1 in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 7)) (5.7.2)
Requirement already satisfied: jupyter-client<8,>=5.3.4 in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 7)) (6.1.12)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 7)) (0.2.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 7)) (5.10.4)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 7)) (7.16.6)
Requirement already satisfied: nest-asyncio>=1.5 in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 7)) (1.6.0)
Requirement already satisfied: ipykernel in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 7)) (6.17.1)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 7)) (1.8.3)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 7)) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 7)) (0.21.1)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.11/dist-packages (from notebook->-r requirements.txt (line 7)) (1.2.0)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.11/dist-packages (from xgboost->-r requirements.txt (line 13)) (2.21.5)
INFO: pip is looking at multiple versions of imbalanced-learn to determine which version is compatible with other requirements. This could take a while.
Collecting imbalanced-learn (from -r requirements.txt (line 15))
  Downloading imbalanced_learn-0.12.4-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic<2->mlflow==2.2.2->-r requirements.txt (line 6)) (1.1.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from astunparse>=1.6.0->tensorflow->-r requirements.txt (line 1)) (0.45.1)
Requirement already satisfied: pyjwt>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from databricks-cli<1,>=0.8.7->mlflow==2.2.2->-r requirements.txt (line 6)) (2.10.1)
Requirement already satisfied: oauthlib>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from databricks-cli<1,>=0.8.7->mlflow==2.2.2->-r requirements.txt (line 6)) (3.2.2)
Requirement already satisfied: urllib3<3,>=1.26.7 in /usr/local/lib/python3.11/dist-packages (from databricks-cli<1,>=0.8.7->mlflow==2.2.2->-r requirements.txt (line 6)) (2.3.0)
Requirement already satisfied: websocket-client>=0.32.0 in /usr/local/lib/python3.11/dist-packages (from docker<7,>=4.0.0->mlflow==2.2.2->-r requirements.txt (line 6)) (1.8.0)
Collecting dictdiffer>=0.8.1 (from dvc-data<3.17,>=3.16.2->dvc->-r requirements.txt (line 4))
  Downloading dictdiffer-0.9.0-py2.py3-none-any.whl.metadata (4.8 kB)
Collecting diskcache>=5.2.1 (from dvc-data<3.17,>=3.16.2->dvc->-r requirements.txt (line 4))
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Collecting sqltrie<1,>=0.11.0 (from dvc-data<3.17,>=3.16.2->dvc->-r requirements.txt (line 4))
  Downloading sqltrie-0.11.2-py3-none-any.whl.metadata (3.3 kB)
Requirement already satisfied: orjson<4,>=3 in /usr/local/lib/python3.11/dist-packages (from dvc-data<3.17,>=3.16.2->dvc->-r requirements.txt (line 4)) (3.10.16)
Collecting aiohttp-retry>=2.5.0 (from dvc-http>=2.29.0->dvc->-r requirements.txt (line 4))
  Downloading aiohttp_retry-2.9.1-py3-none-any.whl.metadata (8.8 kB)
Collecting billiard<5.0,>=4.2.1 (from celery->dvc->-r requirements.txt (line 4))
  Downloading billiard-4.2.1-py3-none-any.whl.metadata (4.4 kB)
Collecting vine<6.0,>=5.1.0 (from celery->dvc->-r requirements.txt (line 4))

# Thư viện

In [3]:
import os
import matplotlib.pyplot as plt
from Mylib import myfuncs
from sklearn.model_selection import train_test_split
import pandas as pd

# Read the dataset

In [4]:
df = pd.read_csv("data/GlobalWeatherRepository.csv")
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [5]:
df.columns

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph',
       'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in',
       'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius',
       'feels_like_fahrenheit', 'visibility_km', 'visibility_miles',
       'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise',
       'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination'],
      dtype='object')

# Xem xét cột target

In [6]:
target_col = "temperature_celsius"

df[target_col].describe()

count    65678.000000
mean        22.085698
std          9.547597
min        -24.900000
25%         16.400000
50%         24.700000
75%         28.400000
max         49.200000
Name: temperature_celsius, dtype: float64

In [7]:
temp_bin = pd.cut(df[target_col], bins = [df[target_col].min()-1, 20, 30, df[target_col].max()+1], labels = ["low", 'medium', 'high'])

temp_bin.value_counts() / len(temp_bin) * 100

temperature_celsius
medium    50.848077
low       32.689790
high      16.462133
Name: count, dtype: float64

In [8]:
df['temp_bin'] = temp_bin

In [9]:
len(temp_bin)

65678

In [10]:
df['temp_bin'].isnull().sum()

0

# CHia dữ liệu thành tập train, tập val, tập test
- 80% -> training
- 10% -> val
- 10% -> test

In [11]:
df = df.sample(frac = 1.0)

train_size = 0.8
val_size = 0.1
num_train = int(train_size * len(df))
num_val = int(val_size * len(df))

df_train = df.iloc[:num_train, :]
df_val = df.iloc[num_train:num_train+num_val, :]
df_test = df.iloc[num_train+num_val:]

In [12]:
df_train.shape, df_val.shape, df_test.shape

((52542, 42), (6567, 42), (6569, 42))

# Lưu dữ liệu

In [13]:
data_folder = "artifacts/data_ingestion"
os.makedirs(data_folder, exist_ok=True)

myfuncs.save_python_object(os.path.join(data_folder, "raw_data.pkl"), df)
myfuncs.save_python_object(os.path.join(data_folder, "train_data.pkl"), df_train)
myfuncs.save_python_object(os.path.join(data_folder, "val_data.pkl"), df_val)
myfuncs.save_python_object(os.path.join(data_folder, "test_data.pkl"), df_test)